### ISSUE TITLE
Add an example of how to manually mirror an image from source to destination for some of the deprecated images in 'openshift' namespace

### ISSUE THREAD

**Issue by jwmatthews** [redhat-cop/openshift-migration-best-practices#62]
Update with an example of how to mirror specific images from source to destination

https://redhat-cop.github.io/openshift-migration-best-practices/04-running-the-migration.html#internal-images

**Comment by jwmatthews** [comment]
cc @dymurray

**Comment by jwmatthews** [comment]
Will be closed via https://github.com/redhat-cop/openshift-migration-best-practices/pull/63

**Comment by apinnick** [comment]
#63 merged.
