### ISSUE TITLE
Create contribution guidelines

### ISSUE THREAD

**Issue by ariescheurwater** [redhat-cop/openshift-migration-best-practices#78]
**Why**
I wanted to contribute, but should not find the guidelines for contributing to this repo.

**What**
Create contribution guidelines for this repo.
https://docs.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors

Examples:
https://github.com/redhat-cop/containers-quickstarts/blob/master/CONTRIBUTING.md
https://github.com/redhat-cop/automation-good-practices/blob/main/CONTRIBUTE.adoc

**Comment by apinnick** [comment]
Guidelines link added.
