### ISSUE TITLE
Broken link 'edit' button on pages

### ISSUE THREAD

**Issue by ariescheurwater** [redhat-cop/openshift-migration-best-practices#79]
On every page there is an 'edit' button to that links back to the GitHub, but the link results into a 404.

**Example**
On the 'Planning' page:
![Screenshot on 01-planning md](https://user-images.githubusercontent.com/16334194/110945770-67588e80-833e-11eb-8f98-2540c80fd712.png)
Source: https://redhat-cop.github.io/openshift-migration-best-practices/01-planning.html

**Comment by apinnick** [comment]
Edit icon removed. Thanks.
